/**
 * LEETCODE NEON - Application Logic
 * Following RAG.md v4.0 Directives
 * Total Problems: 40
 */

(function() {
    'use strict';

    const PROBLEMS = [
        { id: 1, title: 'Two Sum', diff: 'Easy', code: `function twoSum(nums, target) {\n    const map = new Map();\n    for (let i = 0; i < nums.length; i++) {\n        const complement = target - nums[i];\n        if (map.has(complement)) return [map.get(complement), i];\n        map.set(nums[i], i);\n    }\n}` },
        { id: 2, title: 'Valid Parentheses', diff: 'Easy', code: `function isValid(s) {\n    const stack = [];\n    const map = { ")": "(", "}": "{", "]": "[" };\n    for (let char of s) {\n        if (map[char]) {\n            if (stack.pop() !== map[char]) return false;\n        } else stack.push(char);\n    }\n    return stack.length === 0;\n}` },
        { id: 3, title: 'Merge Two Sorted Lists', diff: 'Easy', code: `function mergeTwoLists(l1, l2) {\n    if (!l1 || !l2) return l1 || l2;\n    if (l1.val < l2.val) {\n        l1.next = mergeTwoLists(l1.next, l2);\n        return l1;\n    } else {\n        l2.next = mergeTwoLists(l1, l2.next);\n        return l2;\n    }\n}` },
        { id: 4, title: 'Best Time to Buy and Sell Stock', diff: 'Easy', code: `function maxProfit(prices) {\n    let min = Infinity, max = 0;\n    for (let p of prices) {\n        min = Math.min(min, p);\n        max = Math.max(max, p - min);\n    }\n    return max;\n}` },
        { id: 5, title: 'Valid Palindrome', diff: 'Easy', code: `function isPalindrome(s) {\n    s = s.toLowerCase().replace(/[^a-z0-9]/g, "");\n    return s === s.split("").reverse().join("");\n}` },
        { id: 6, title: 'Invert Binary Tree', diff: 'Easy', code: `function invertTree(root) {\n    if (!root) return null;\n    [root.left, root.right] = [invertTree(root.right), invertTree(root.left)];\n    return root;\n}` },
        { id: 7, title: 'Valid Anagram', diff: 'Easy', code: `function isAnagram(s, t) {\n    if (s.length !== t.length) return false;\n    const count = {};\n    for (let char of s) count[char] = (count[char] || 0) + 1;\n    for (let char of t) {\n        if (!count[char]) return false;\n        count[char]--;\n    }\n    return true;\n}` },
        { id: 8, title: 'Binary Search', diff: 'Easy', code: `function search(nums, target) {\n    let lo = 0, hi = nums.length - 1;\n    while (lo <= hi) {\n        let mid = lo + Math.floor((hi - lo) / 2);\n        if (nums[mid] === target) return mid;\n        if (nums[mid] < target) lo = mid + 1;\n        else hi = mid - 1;\n    }\n    return -1;\n}` },
        { id: 9, title: 'Flood Fill', diff: 'Easy', code: `function floodFill(image, sr, sc, newColor) {\n    const oldColor = image[sr][sc];\n    if (oldColor === newColor) return image;\n    function dfs(r, c) {\n        if (r < 0 || r >= image.length || c < 0 || c >= image[0].length || image[r][c] !== oldColor) return;\n        image[r][c] = newColor;\n        dfs(r+1, c); dfs(r-1, c); dfs(r, c+1); dfs(r, c-1);\n    }\n    dfs(sr, sc);\n    return image;\n}` },
        { id: 10, title: 'Maximum Subarray', diff: 'Medium', code: `function maxSubArray(nums) {\n    let max = -Infinity, sum = 0;\n    for (let n of nums) {\n        sum = Math.max(n, sum + n);\n        max = Math.max(max, sum);\n    }\n    return max;\n}` },
        { id: 11, title: 'Lowest Common Ancestor of a BST', diff: 'Medium', code: `function lowestCommonAncestor(root, p, q) {\n    if (p.val < root.val && q.val < root.val) return lowestCommonAncestor(root.left, p, q);\n    if (p.val > root.val && q.val > root.val) return lowestCommonAncestor(root.right, p, q);\n    return root;\n}` },
        { id: 12, title: 'Balanced Binary Tree', diff: 'Easy', code: `function isBalanced(root) {\n    function height(node) {\n        if (!node) return 0;\n        let left = height(node.left), right = height(node.right);\n        if (left === -1 || right === -1 || Math.abs(left - right) > 1) return -1;\n        return Math.max(left, right) + 1;\n    }\n    return height(root) !== -1;\n}` },
        { id: 13, title: 'Linked List Cycle', diff: 'Easy', code: `function hasCycle(head) {\n    let slow = head, fast = head;\n    while (fast && fast.next) {\n        slow = slow.next;\n        fast = fast.next.next;\n        if (slow === fast) return true;\n    }\n    return false;\n}` },
        { id: 14, title: 'Implement Queue using Stacks', diff: 'Easy', code: `class MyQueue {\n    constructor() { this.s1 = []; this.s2 = []; }\n    push(x) { this.s1.push(x); }\n    pop() {\n        if (!this.s2.length) while (this.s1.length) this.s2.push(this.s1.pop());\n        return this.s2.pop();\n    }\n}` },
        { id: 15, title: 'First Bad Version', diff: 'Easy', code: `function solution(isBadVersion) {\n    return function(n) {\n        let lo = 1, hi = n;\n        while (lo < hi) {\n            let mid = lo + Math.floor((hi - lo) / 2);\n            if (isBadVersion(mid)) hi = mid;\n            else lo = mid + 1;\n        }\n        return lo;\n    };\n}` },
        { id: 16, title: 'Ransom Note', diff: 'Easy', code: `function canConstruct(ransomNote, magazine) {\n    const count = {};\n    for (let char of magazine) count[char] = (count[char] || 0) + 1;\n    for (let char of ransomNote) {\n        if (!count[char]) return false;\n        count[char]--;\n    }\n    return true;\n}` },
        { id: 17, title: 'Climbing Stairs', diff: 'Easy', code: `function climbStairs(n) {\n    let a = 1, b = 1;\n    while (n--) [a, b] = [b, a + b];\n    return a;\n}` },
        { id: 18, title: 'Longest Palindrome', diff: 'Easy', code: `function longestPalindrome(s) {\n    const set = new Set();\n    let len = 0;\n    for (let char of s) {\n        if (set.has(char)) { len += 2; set.delete(char); }\n        else set.add(char);\n    }\n    return len + (set.size > 0 ? 1 : 0);\n}` },
        { id: 19, title: 'Reverse Linked List', diff: 'Easy', code: `function reverseList(head) {\n    let prev = null, curr = head;\n    while (curr) {\n        let next = curr.next;\n        curr.next = prev;\n        prev = curr;\n        curr = next;\n    }\n    return prev;\n}` },
        { id: 20, title: 'Majority Element', diff: 'Easy', code: `function majorityElement(nums) {\n    let count = 0, candidate = null;\n    for (let n of nums) {\n        if (count === 0) candidate = n;\n        count += (n === candidate) ? 1 : -1;\n    }\n    return candidate;\n}` },
        // 20 NEW PROBLEMS
        { id: 21, title: 'Diameter of Binary Tree', diff: 'Easy', code: `function diameterOfBinaryTree(root) {\n    let max = 0;\n    function depth(node) {\n        if (!node) return 0;\n        let left = depth(node.left), right = depth(node.right);\n        max = Math.max(max, left + right);\n        return Math.max(left, right) + 1;\n    }\n    depth(root);\n    return max;\n}` },
        { id: 22, title: 'Middle of the Linked List', diff: 'Easy', code: `function middleNode(head) {\n    let slow = head, fast = head;\n    while (fast && fast.next) {\n        slow = slow.next;\n        fast = fast.next.next;\n    }\n    return slow;\n}` },
        { id: 23, title: 'Maximum Depth of Binary Tree', diff: 'Easy', code: `function maxDepth(root) {\n    if (!root) return 0;\n    return Math.max(maxDepth(root.left), maxDepth(root.right)) + 1;\n}` },
        { id: 24, title: 'Contains Duplicate', diff: 'Easy', code: `function containsDuplicate(nums) {\n    return new Set(nums).size !== nums.length;\n}` },
        { id: 25, title: 'Backspace String Compare', diff: 'Easy', code: `function backspaceCompare(s, t) {\n    const build = str => {\n        const res = [];\n        for (let char of str) {\n            if (char === "#") res.pop();\n            else res.push(char);\n        }\n        return res.join("");\n    };\n    return build(s) === build(t);\n}` },
        { id: 26, title: 'Counting Bits', diff: 'Easy', code: `function countBits(n) {\n    const res = new Array(n + 1).fill(0);\n    for (let i = 1; i <= n; i++) res[i] = res[i >> 1] + (i & 1);\n    return res;\n}` },
        { id: 27, title: 'Same Tree', diff: 'Easy', code: `function isSameTree(p, q) {\n    if (!p && !q) return true;\n    if (!p || !q || p.val !== q.val) return false;\n    return isSameTree(p.left, q.left) && isSameTree(p.right, q.right);\n}` },
        { id: 28, title: 'Number of 1 Bits', diff: 'Easy', code: `function hammingWeight(n) {\n    let count = 0;\n    while (n !== 0) {\n        n &= (n - 1);\n        count++;\n    }\n    return count;\n}` },
        { id: 29, title: 'Longest Common Prefix', diff: 'Easy', code: `function longestCommonPrefix(strs) {\n    if (!strs.length) return "";\n    let prefix = strs[0];\n    for (let i = 1; i < strs.length; i++) {\n        while (strs[i].indexOf(prefix) !== 0) {\n            prefix = prefix.substring(0, prefix.length - 1);\n        }\n    }\n    return prefix;\n}` },
        { id: 30, title: 'Single Number', diff: 'Easy', code: `function singleNumber(nums) {\n    let res = 0;\n    for (let n of nums) res ^= n;\n    return res;\n}` },
        { id: 31, title: 'Move Zeroes', diff: 'Easy', code: `function moveZeroes(nums) {\n    let last = 0;\n    for (let i = 0; i < nums.length; i++) {\n        if (nums[i] !== 0) [nums[last++], nums[i]] = [nums[i], nums[last]];\n    }\n}` },
        { id: 32, title: 'Symmetric Tree', diff: 'Easy', code: `function isSymmetric(root) {\n    function isMirror(t1, t2) {\n        if (!t1 && !t2) return true;\n        if (!t1 || !t2) return false;\n        return t1.val === t2.val && isMirror(t1.left, t2.right) && isMirror(t1.right, t2.left);\n    }\n    return isMirror(root, root);\n}` },
        { id: 33, title: 'Missing Number', diff: 'Easy', code: `function missingNumber(nums) {\n    let sum = nums.length * (nums.length + 1) / 2;\n    return sum - nums.reduce((a, b) => a + b, 0);\n}` },
        { id: 34, title: 'Palindrome Linked List', diff: 'Easy', code: `function isPalindrome(head) {\n    let slow = head, fast = head, prev = null;\n    while (fast && fast.next) {\n        slow = slow.next;\n        fast = fast.next.next;\n    }\n    while (slow) {\n        let next = slow.next;\n        slow.next = prev; prev = slow; slow = next;\n    }\n    while (prev) {\n        if (prev.val !== head.val) return false;\n        prev = prev.next; head = head.next;\n    }\n    return true;\n}` },
        { id: 35, title: 'Convert Sorted Array to BST', diff: 'Easy', code: `function sortedArrayToBST(nums) {\n    if (!nums.length) return null;\n    let mid = Math.floor(nums.length / 2);\n    let root = new TreeNode(nums[mid]);\n    root.left = sortedArrayToBST(nums.slice(0, mid));\n    root.right = sortedArrayToBST(nums.slice(mid + 1));\n    return root;\n}` },
        { id: 36, title: 'Reverse String', diff: 'Easy', code: `function reverseString(s) {\n    let lo = 0, hi = s.length - 1;\n    while (lo < hi) [s[lo++], s[hi--]] = [s[hi], s[lo]];\n}` },
        { id: 37, title: 'Intersection of Two Linked Lists', diff: 'Easy', code: `function getIntersectionNode(headA, headB) {\n    let a = headA, b = headB;\n    while (a !== b) {\n        a = a ? a.next : headB;\n        b = b ? b.next : headA;\n    }\n    return a;\n}` },
        { id: 38, title: 'Power of Three', diff: 'Easy', code: `function isPowerOfThree(n) {\n    return n > 0 && 1162261467 % n === 0;\n}` },
        { id: 39, title: 'Happy Number', diff: 'Easy', code: `function isHappy(n) {\n    const seen = new Set();\n    while (n !== 1 && !seen.has(n)) {\n        seen.add(n);\n        n = String(n).split("").reduce((s, d) => s + d*d, 0);\n    }\n    return n === 1;\n}` },
        { id: 40, title: 'Pascal\'s Triangle', diff: 'Easy', code: `function generate(numRows) {\n    const res = [];\n    for (let i = 0; i < numRows; i++) {\n        res[i] = new Array(i + 1).fill(1);\n        for (let j = 1; j < i; j++) {\n            res[i][j] = res[i-1][j-1] + res[i-1][j];\n        }\n    }\n    return res;\n}` },
        // 30 NEW PROBLEMS (Total 70)
        { id: 41, title: 'Subtree of Another Tree', diff: 'Easy', code: `function isSubtree(root, subRoot) {\n    if (!root) return false;\n    if (isSame(root, subRoot)) return true;\n    return isSubtree(root.left, subRoot) || isSubtree(root.right, subRoot);\n    function isSame(s, t) {\n        if (!s || !t) return s === t;\n        return s.val === t.val && isSame(s.left, t.left) && isSame(s.right, t.right);\n    }\n}` },
        { id: 42, title: 'Kth Smallest Element in a BST', diff: 'Medium', code: `function kthSmallest(root, k) {\n    const stack = [];\n    while (true) {\n        while (root) {\n            stack.push(root);\n            root = root.left;\n        }\n        root = stack.pop();\n        if (--k === 0) return root.val;\n        root = root.right;\n    }\n}` },
        { id: 43, title: 'Binary Tree Level Order Traversal', diff: 'Medium', code: `function levelOrder(root) {\n    if (!root) return [];\n    const res = [], q = [root];\n    while (q.length) {\n        let len = q.length, level = [];\n        while (len--) {\n            let n = q.shift();\n            level.push(n.val);\n            if (n.left) q.push(n.left);\n            if (n.right) q.push(n.right);\n        }\n        res.push(level);\n    }\n    return res;\n}` },
        { id: 44, title: 'Rotate Image', diff: 'Medium', code: `function rotate(matrix) {\n    matrix.reverse();\n    for (let i = 0; i < matrix.length; i++) {\n        for (let j = i + 1; j < matrix[i].length; j++) {\n            [matrix[i][j], matrix[j][i]] = [matrix[j][i], matrix[i][j]];\n        }\n    }\n}` },
        { id: 45, title: 'Group Anagrams', diff: 'Medium', code: `function groupAnagrams(strs) {\n    const map = {};\n    for (let s of strs) {\n        const key = s.split("").sort().join("");\n        if (!map[key]) map[key] = [];\n        map[key].push(s);\n    }\n    return Object.values(map);\n}` },
        { id: 46, title: 'Longest Consecutive Sequence', diff: 'Medium', code: `function longestConsecutive(nums) {\n    const set = new Set(nums);\n    let max = 0;\n    for (let n of set) {\n        if (!set.has(n - 1)) {\n            let curr = n, count = 1;\n            while (set.has(curr + 1)) { curr++; count++; }\n            max = Math.max(max, count);\n        }\n    }\n    return max;\n}` },
        { id: 47, title: 'Word Search', diff: 'Medium', code: `function exist(board, word) {\n    for (let i = 0; i < board.length; i++) {\n        for (let j = 0; j < board[0].length; j++) {\n            if (dfs(i, j, 0)) return true;\n        }\n    }\n    return false;\n    function dfs(r, c, i) {\n        if (i === word.length) return true;\n        if (r < 0 || r >= board.length || c < 0 || c >= board[0].length || board[r][c] !== word[i]) return false;\n        const tmp = board[r][c];\n        board[r][c] = "#";\n        const found = dfs(r+1, c, i+1) || dfs(r-1, c, i+1) || dfs(r, c+1, i+1) || dfs(r, c-1, i+1);\n        board[r][c] = tmp;\n        return found;\n    }\n}` },
        { id: 48, title: 'Course Schedule', diff: 'Medium', code: `function canFinish(numCourses, prerequisites) {\n    const adj = Array.from({length: numCourses}, () => []);\n    for (let [u, v] of prerequisites) adj[v].push(u);\n    const visit = new Array(numCourses).fill(0);\n    for (let i = 0; i < numCourses; i++) if (hasCycle(i)) return false;\n    return true;\n    function hasCycle(i) {\n        if (visit[i] === 1) return true;\n        if (visit[i] === 2) return false;\n        visit[i] = 1;\n        for (let next of adj[i]) if (hasCycle(next)) return true;\n        visit[i] = 2;\n        return false;\n    }\n}` },
        { id: 49, title: 'Implement Trie (Prefix Tree)', diff: 'Medium', code: `class Trie {\n    constructor() { this.root = {}; }\n    insert(word) {\n        let node = this.root;\n        for (let c of word) node = node[c] = node[c] || {};\n        node.isEnd = true;\n    }\n    search(word) {\n        let node = this.traverse(word);\n        return !!node && !!node.isEnd;\n    }\n    startsWith(prefix) {\n        return !!this.traverse(prefix);\n    }\n    traverse(word) {\n        let node = this.root;\n        for (let c of word) {\n            node = node[c];\n            if (!node) return null;\n        }\n        return node;\n    }\n}` },
        { id: 50, title: 'Coin Change', diff: 'Medium', code: `function coinChange(coins, amount) {\n    const dp = new Array(amount + 1).fill(Infinity);\n    dp[0] = 0;\n    for (let i = 1; i <= amount; i++) {\n        for (let c of coins) {\n            if (i >= c) dp[i] = Math.min(dp[i], dp[i - c] + 1);\n        }\n    }\n    return dp[amount] === Infinity ? -1 : dp[amount];\n}` },
        { id: 51, title: 'Product of Array Except Self', diff: 'Medium', code: `function productExceptSelf(nums) {\n    const res = [], n = nums.length;\n    let left = 1, right = 1;\n    for (let i = 0; i < n; i++) { res[i] = left; left *= nums[i]; }\n    for (let i = n - 1; i >= 0; i--) { res[i] *= right; right *= nums[i]; }\n    return res;\n}` },
        { id: 52, title: 'Min Stack', diff: 'Medium', code: `class MinStack {\n    constructor() { this.stack = []; this.min = []; }\n    push(val) {\n        this.stack.push(val);\n        this.min.push(Math.min(val, this.min[this.min.length-1] ?? Infinity));\n    }\n    pop() { this.stack.pop(); this.min.pop(); }\n    top() { return this.stack[this.stack.length-1]; }\n    getMin() { return this.min[this.min.length-1]; }\n}` },
        { id: 53, title: 'Validate Binary Search Tree', diff: 'Medium', code: `function isValidBST(root, min = -Infinity, max = Infinity) {\n    if (!root) return true;\n    if (root.val <= min || root.val >= max) return false;\n    return isValidBST(root.left, min, root.val) && isValidBST(root.right, root.val, max);\n}` },
        { id: 54, title: 'Number of Islands', diff: 'Medium', code: `function numIslands(grid) {\n    let count = 0;\n    for (let i = 0; i < grid.length; i++) {\n        for (let j = 0; j < grid[0].length; j++) {\n            if (grid[i][j] === "1") { count++; dfs(i, j); }\n        }\n    }\n    return count;\n    function dfs(r, c) {\n        if (r < 0 || r >= grid.length || c < 0 || c >= grid[0].length || grid[r][c] === "0") return;\n        grid[r][c] = "0";\n        dfs(r+1, c); dfs(r-1, c); dfs(r, c+1); dfs(r, c-1);\n    }\n}` },
        { id: 55, title: 'Rotting Oranges', diff: 'Medium', code: `function orangesRotting(grid) {\n    const q = [];\n    let fresh = 0, mins = 0;\n    for (let i = 0; i < grid.length; i++) {\n        for (let j = 0; j < grid[0].length; j++) {\n            if (grid[i][j] === 2) q.push([i, j]);\n            if (grid[i][j] === 1) fresh++;\n        }\n    }\n    const dirs = [[1,0],[-1,0],[0,1],[0,-1]];\n    while (q.length && fresh > 0) {\n        let size = q.length;\n        while (size--) {\n            let [r, c] = q.shift();\n            for (let [dr, dc] of dirs) {\n                let nr = r + dr, nc = c + dc;\n                if (nr >= 0 && nr < grid.length && nc >= 0 && nc < grid[0].length && grid[nr][nc] === 1) {\n                    grid[nr][nc] = 2; fresh--; q.push([nr, nc]);\n                }\n            }\n        }\n        mins++;\n    }\n    return fresh === 0 ? mins : -1;\n}` },
        { id: 56, title: 'Search in Rotated Sorted Array', diff: 'Medium', code: `function search(nums, target) {\n    let lo = 0, hi = nums.length - 1;\n    while (lo <= hi) {\n        let mid = Math.floor((lo + hi) / 2);\n        if (nums[mid] === target) return mid;\n        if (nums[lo] <= nums[mid]) {\n            if (target >= nums[lo] && target < nums[mid]) hi = mid - 1;\n            else lo = mid + 1;\n        } else {\n            if (target > nums[mid] && target <= nums[hi]) lo = mid + 1;\n            else hi = mid - 1;\n        }\n    }\n    return -1;\n}` },
        { id: 57, title: 'Combination Sum', diff: 'Medium', code: `function combinationSum(candidates, target) {\n    const res = [];\n    dfs(0, target, []);\n    return res;\n    function dfs(start, rem, path) {\n        if (rem === 0) { res.push([...path]); return; }\n        for (let i = start; i < candidates.length; i++) {\n            if (rem >= candidates[i]) {\n                path.push(candidates[i]);\n                dfs(i, rem - candidates[i], path);\n                path.pop();\n            }\n        }\n    }\n}` },
        { id: 58, title: 'Permutations', diff: 'Medium', code: `function permute(nums) {\n    const res = [];\n    dfs([]);\n    return res;\n    function dfs(path) {\n        if (path.length === nums.length) { res.push([...path]); return; }\n        for (let n of nums) {\n            if (!path.includes(n)) {\n                path.push(n);\n                dfs(path);\n                path.pop();\n            }\n        }\n    }\n}` },
        { id: 59, title: 'Merge Intervals', diff: 'Medium', code: `function merge(intervals) {\n    intervals.sort((a, b) => a[0] - b[0]);\n    const res = [intervals[0]];\n    for (let i = 1; i < intervals.length; i++) {\n        let last = res[res.length - 1];\n        if (intervals[i][0] <= last[1]) last[1] = Math.max(last[1], intervals[i][1]);\n        else res.push(intervals[i]);\n    }\n    return res;\n}` },
        { id: 60, title: 'Lowest Common Ancestor of a Binary Tree', diff: 'Medium', code: `function lowestCommonAncestor(root, p, q) {\n    if (!root || root === p || root === q) return root;\n    let left = lowestCommonAncestor(root.left, p, q);\n    let right = lowestCommonAncestor(root.right, p, q);\n    if (left && right) return root;\n    return left || right;\n}` },
        { id: 61, title: 'Time Based Key-Value Store', diff: 'Medium', code: `class TimeMap {\n    constructor() { this.map = {}; }\n    set(key, value, timestamp) {\n        if (!this.map[key]) this.map[key] = [];\n        this.map[key].push({ value, timestamp });\n    }\n    get(key, timestamp) {\n        const vals = this.map[key];\n        if (!vals) return "";\n        let lo = 0, hi = vals.length - 1, res = "";\n        while (lo <= hi) {\n            let mid = Math.floor((lo + hi) / 2);\n            if (vals[mid].timestamp <= timestamp) { res = vals[mid].value; lo = mid + 1; }\n            else hi = mid - 1;\n        }\n        return res;\n    }\n}` },
        { id: 62, title: 'Accounts Merge', diff: 'Medium', code: `function accountsMerge(accounts) {\n    const parents = {}, emailToName = {};\n    function find(i) { return parents[i] === i ? i : parents[i] = find(parents[i]); }\n    function union(i, j) { parents[find(i)] = find(j); }\n    for (let [name, ...emails] of accounts) {\n        for (let email of emails) {\n            if (!parents[email]) parents[email] = email;\n            emailToName[email] = name;\n            union(email, emails[0]);\n        }\n    }\n    const groups = {};\n    for (let email in parents) {\n        let root = find(email);\n        if (!groups[root]) groups[root] = [];\n        groups[root].push(email);\n    }\n    return Object.entries(groups).map(([root, emails]) => [emailToName[root], ...emails.sort()]);\n}` },
        { id: 63, title: 'Sort Colors', diff: 'Medium', code: `function sortColors(nums) {\n    let lo = 0, mid = 0, hi = nums.length - 1;\n    while (mid <= hi) {\n        if (nums[mid] === 0) [nums[lo++], nums[mid++]] = [nums[mid], nums[lo]];\n        else if (nums[mid] === 1) mid++;\n        else [nums[mid], nums[hi--]] = [nums[hi], nums[mid]];\n    }\n}` },
        { id: 64, title: 'Word Break', diff: 'Medium', code: `function wordBreak(s, wordDict) {\n    const dp = new Array(s.length + 1).fill(false);\n    dp[0] = true;\n    for (let i = 1; i <= s.length; i++) {\n        for (let w of wordDict) {\n            if (dp[i - w.length] && s.slice(i - w.length, i) === w) {\n                dp[i] = true; break;\n            }\n        }\n    }\n    return dp[s.length];\n}` },
        { id: 65, title: 'String to Integer (atoi)', diff: 'Medium', code: `function myAtoi(s) {\n    let i = 0, sign = 1, res = 0;\n    while (s[i] === " ") i++;\n    if (s[i] === "+" || s[i] === "-") sign = s[i++] === "-" ? -1 : 1;\n    while (i < s.length && s[i] >= "0" && s[i] <= "9") {\n        res = res * 10 + (s[i++] - "0");\n    }\n    res *= sign;\n    return Math.max(-(2**31), Math.min(res, 2**31 - 1));\n}` },
        { id: 66, title: 'Longest Palindromic Substring', diff: 'Medium', code: `function longestPalindrome(s) {\n    let start = 0, maxLen = 0;\n    for (let i = 0; i < s.length; i++) {\n        expand(i, i); expand(i, i + 1);\n    }\n    function expand(l, r) {\n        while (l >= 0 && r < s.length && s[l] === s[r]) {\n            if (r - l + 1 > maxLen) {\n                start = l; maxLen = r - l + 1;\n            }\n            l--; r++;\n        }\n    }\n    return s.substring(start, start + maxLen);\n}` },
        { id: 67, title: 'Unique Paths', diff: 'Medium', code: `function uniquePaths(m, n) {\n    const dp = new Array(n).fill(1);\n    for (let i = 1; i < m; i++) {\n        for (let j = 1; j < n; j++) dp[j] += dp[j - 1];\n    }\n    return dp[n - 1];\n}` },
        { id: 68, title: 'Spiral Matrix', diff: 'Medium', code: `function spiralOrder(matrix) {\n    const res = [];\n    let top = 0, bottom = matrix.length - 1, left = 0, right = matrix[0].length - 1;\n    while (top <= bottom && left <= right) {\n        for (let i = left; i <= right; i++) res.push(matrix[top][i]);\n        top++;\n        for (let i = top; i <= bottom; i++) res.push(matrix[i][right]);\n        right--;\n        if (top <= bottom) for (let i = right; i >= left; i--) res.push(matrix[bottom][i]);\n        bottom--;\n        if (left <= right) for (let i = bottom; i >= top; i--) res.push(matrix[i][left]);\n        left++;\n    }\n    return res;\n}` },
        { id: 69, title: 'Subsets', diff: 'Medium', code: `function subsets(nums) {\n    const res = [[]];\n    for (let n of nums) {\n        let size = res.length;\n        for (let i = 0; i < size; i++) res.push([...res[i], n]);\n    }\n    return res;\n}` },
        { id: 70, title: 'Binary Tree Right Side View', diff: 'Medium', code: `function rightSideView(root) {\n    const res = [];\n    dfs(root, 0);\n    return res;\n    function dfs(node, depth) {\n        if (!node) return;\n        if (depth === res.length) res.push(node.val);\n        dfs(node.right, depth + 1);\n        dfs(node.left, depth + 1);\n    }\n}` },
        // 30 NEW PROBLEMS (Total 100)
        { id: 71, title: 'Word Search II', diff: 'Hard', code: `function findWords(board, words) {\n    const res = [], root = {};\n    for (let w of words) {\n        let node = root;\n        for (let c of w) node = node[c] = node[c] || {};\n        node.word = w;\n    }\n    for (let i = 0; i < board.length; i++) {\n        for (let j = 0; j < board[0].length; j++) dfs(i, j, root);\n    }\n    return res;\n    function dfs(r, c, node) {\n        if (!node[board[r][c]]) return;\n        node = node[board[r][c]];\n        if (node.word) { res.push(node.word); node.word = null; }\n        let tmp = board[r][c]; board[r][c] = "#";\n        if (r > 0) dfs(r-1, c, node);\n        if (r < board.length - 1) dfs(r+1, c, node);\n        if (c > 0) dfs(r, c-1, node);\n        if (c < board[0].length - 1) dfs(r, c+1, node);\n        board[r][c] = tmp;\n    }\n}` },
        { id: 72, title: 'Median of Two Sorted Arrays', diff: 'Hard', code: `function findMedianSortedArrays(nums1, nums2) {\n    if (nums1.length > nums2.length) [nums1, nums2] = [nums2, nums1];\n    let m = nums1.length, n = nums2.length, lo = 0, hi = m;\n    while (lo <= hi) {\n        let i = Math.floor((lo + hi) / 2), j = Math.floor((m + n + 1) / 2) - i;\n        let maxL1 = i === 0 ? -Infinity : nums1[i-1], minR1 = i === m ? Infinity : nums1[i];\n        let maxL2 = j === 0 ? -Infinity : nums2[j-1], minR2 = j === n ? Infinity : nums2[j];\n        if (maxL1 <= minR2 && maxL2 <= minR1) {\n            if ((m + n) % 2 === 0) return (Math.max(maxL1, maxL2) + Math.min(minR1, minR2)) / 2;\n            return Math.max(maxL1, maxL2);\n        } else if (maxL1 > minR2) hi = i - 1;\n        else lo = i + 1;\n    }\n}` },
        { id: 73, title: 'Longest Valid Parentheses', diff: 'Hard', code: `function longestValidParentheses(s) {\n    const stack = [-1];\n    let max = 0;\n    for (let i = 0; i < s.length; i++) {\n        if (s[i] === "(") stack.push(i);\n        else {\n            stack.pop();\n            if (stack.length === 0) stack.push(i);\n            else max = Math.max(max, i - stack[stack.length - 1]);\n        }\n    }\n    return max;\n}` },
        { id: 74, title: 'Edit Distance', diff: 'Hard', code: `function minDistance(w1, w2) {\n    const m = w1.length, n = w2.length, dp = Array.from({length: m + 1}, () => []);\n    for (let i = 0; i <= m; i++) dp[i][0] = i;\n    for (let j = 0; j <= n; j++) dp[0][j] = j;\n    for (let i = 1; i <= m; i++) {\n        for (let j = 1; j <= n; j++) {\n            if (w1[i-1] === w2[j-1]) dp[i][j] = dp[i-1][j-1];\n            else dp[i][j] = Math.min(dp[i-1][j-1], dp[i-1][j], dp[i][j-1]) + 1;\n        }\n    }\n    return dp[m][n];\n}` },
        { id: 75, title: 'Trapping Rain Water', diff: 'Hard', code: `function trap(height) {\n    let l = 0, r = height.length - 1, lMax = 0, rMax = 0, res = 0;\n    while (l < r) {\n        if (height[l] < height[r]) {\n            height[l] >= lMax ? (lMax = height[l]) : res += (lMax - height[l]);\n            l++;\n        } else {\n            height[r] >= rMax ? (rMax = height[r]) : res += (rMax - height[r]);\n            r--;\n        }\n    }\n    return res;\n}` },
        { id: 76, title: 'Binary Tree Maximum Path Sum', diff: 'Hard', code: `function maxPathSum(root) {\n    let max = -Infinity;\n    function dfs(node) {\n        if (!node) return 0;\n        let l = Math.max(0, dfs(node.left)), r = Math.max(0, dfs(node.right));\n        max = Math.max(max, node.val + l + r);\n        return node.val + Math.max(l, r);\n    }\n    dfs(root);\n    return max;\n}` },
        { id: 77, title: 'N-Queens', diff: 'Hard', code: `function solveNQueens(n) {\n    const res = [], board = Array.from({length: n}, () => ".".repeat(n));\n    const cols = new Set(), d1 = new Set(), d2 = new Set();\n    dfs(0);\n    return res;\n    function dfs(r) {\n        if (r === n) { res.push([...board]); return; }\n        for (let c = 0; c < n; c++) {\n            if (cols.has(c) || d1.has(r-c) || d2.has(r+c)) continue;\n            cols.add(c); d1.add(r-c); d2.add(r+c);\n            let row = board[r].split(""); row[c] = "Q"; board[r] = row.join("");\n            dfs(r + 1);\n            row[c] = "."; board[r] = row.join("");\n            cols.delete(c); d1.delete(r-c); d2.delete(r+c);\n        }\n    }\n}` },
        { id: 78, title: 'Merge k Sorted Lists', diff: 'Hard', code: `function mergeKLists(lists) {\n    if (!lists.length) return null;\n    while (lists.length > 1) {\n        let a = lists.shift(), b = lists.shift();\n        lists.push(merge(a, b));\n    }\n    return lists[0];\n    function merge(l1, l2) {\n        if (!l1 || !l2) return l1 || l2;\n        if (l1.val < l2.val) { l1.next = merge(l1.next, l2); return l1; }\n        else { l2.next = merge(l1, l2.next); return l2; }\n    }\n}` },
        { id: 79, title: 'Regular Expression Matching', diff: 'Hard', code: `function isMatch(s, p) {\n    const dp = Array.from({length: s.length + 1}, () => new Array(p.length + 1).fill(false));\n    dp[0][0] = true;\n    for (let j = 1; j <= p.length; j++) if (p[j-1] === "*") dp[0][j] = dp[0][j-2];\n    for (let i = 1; i <= s.length; i++) {\n        for (let j = 1; j <= p.length; j++) {\n            if (p[j-1] === s[i-1] || p[j-1] === ".") dp[i][j] = dp[i-1][j-1];\n            else if (p[j-1] === "*") {\n                dp[i][j] = dp[i][j-2];\n                if (p[j-2] === s[i-1] || p[j-2] === ".") dp[i][j] = dp[i][j] || dp[i-1][j];\n            }\n        }\n    }\n    return dp[s.length][p.length];\n}` },
        { id: 80, title: 'Sliding Window Maximum', diff: 'Hard', code: `function maxSlidingWindow(nums, k) {\n    const q = [], res = [];\n    for (let i = 0; i < nums.length; i++) {\n        while (q.length && nums[q[q.length-1]] <= nums[i]) q.pop();\n        q.push(i);\n        if (q[0] === i - k) q.shift();\n        if (i >= k - 1) res.push(nums[q[0]]);\n    }\n    return res;\n}` },
        { id: 81, title: 'Jump Game', diff: 'Medium', code: `function canJump(nums) {\n    let goal = nums.length - 1;\n    for (let i = nums.length - 2; i >= 0; i--) {\n        if (i + nums[i] >= goal) goal = i;\n    }\n    return goal === 0;\n}` },
        { id: 82, title: 'Unique Binary Search Trees', diff: 'Medium', code: `function numTrees(n) {\n    const dp = new Array(n + 1).fill(0);\n    dp[0] = 1; dp[1] = 1;\n    for (let i = 2; i <= n; i++) {\n        for (let j = 1; j <= i; j++) dp[i] += dp[j - 1] * dp[i - j];\n    }\n    return dp[n];\n}` },
        { id: 83, title: 'Interleaving String', diff: 'Medium', code: `function isInterleave(s1, s2, s3) {\n    if (s1.length + s2.length !== s3.length) return false;\n    const dp = Array.from({length: s1.length + 1}, () => new Array(s2.length + 1).fill(false));\n    for (let i = 0; i <= s1.length; i++) {\n        for (let j = 0; j <= s2.length; j++) {\n            if (i === 0 && j === 0) dp[i][j] = true;\n            else if (i === 0) dp[i][j] = dp[i][j-1] && s2[j-1] === s3[i+j-1];\n            else if (j === 0) dp[i][j] = dp[i-1][j] && s1[i-1] === s3[i+j-1];\n            else dp[i][j] = (dp[i-1][j] && s1[i-1] === s3[i+j-1]) || (dp[i][j-1] && s2[j-1] === s3[i+j-1]);\n        }\n    }\n    return dp[s1.length][s2.length];\n}` },
        { id: 84, title: 'Largest Rectangle in Histogram', diff: 'Hard', code: `function largestRectangleArea(heights) {\n    const stack = [-1]; let max = 0;\n    for (let i = 0; i < heights.length; i++) {\n        while (stack[stack.length-1] !== -1 && heights[stack[stack.length-1]] >= heights[i]) {\n            max = Math.max(max, heights[stack.pop()] * (i - stack[stack.length-1] - 1));\n        }\n        stack.push(i);\n    }\n    while (stack[stack.length-1] !== -1) {\n        max = Math.max(max, heights[stack.pop()] * (heights.length - stack[stack.length-1] - 1));\n    }\n    return max;\n}` },
        { id: 85, title: 'Maximal Rectangle', diff: 'Hard', code: `function maximalRectangle(matrix) {\n    if (!matrix.length) return 0;\n    const dp = new Array(matrix[0].length).fill(0); let max = 0;\n    for (let r = 0; r < matrix.length; r++) {\n        for (let c = 0; c < matrix[0].length; c++) dp[c] = matrix[r][c] === "1" ? dp[c] + 1 : 0;\n        max = Math.max(max, largestRectangleArea(dp));\n    }\n    return max;\n}` },
        { id: 86, title: 'Palindrome Partitioning', diff: 'Medium', code: `function partition(s) {\n    const res = [];\n    dfs(0, []);\n    return res;\n    function dfs(start, path) {\n        if (start === s.length) { res.push([...path]); return; }\n        for (let i = start + 1; i <= s.length; i++) {\n            let sub = s.substring(start, i);\n            if (isPal(sub)) { path.push(sub); dfs(i, path); path.pop(); }\n        }\n    }\n    function isPal(str) { return str === str.split("").reverse().join(""); }\n}` },
        { id: 87, title: 'Gas Station', diff: 'Medium', code: `function canCompleteCircuit(gas, cost) {\n    let total = 0, curr = 0, start = 0;\n    for (let i = 0; i < gas.length; i++) {\n        total += gas[i] - cost[i];\n        curr += gas[i] - cost[i];\n        if (curr < 0) { start = i + 1; curr = 0; }\n    }\n    return total >= 0 ? start : -1;\n}` },
        { id: 88, title: 'Candy', diff: 'Hard', code: `function candy(ratings) {\n    const res = new Array(ratings.length).fill(1);\n    for (let i = 1; i < ratings.length; i++) if (ratings[i] > ratings[i-1]) res[i] = res[i-1] + 1;\n    for (let i = ratings.length - 2; i >= 0; i--) if (ratings[i] > ratings[i+1]) res[i] = Math.max(res[i], res[i+1] + 1);\n    return res.reduce((a, b) => a + b, 0);\n}` },
        { id: 89, title: 'Copy List with Random Pointer', diff: 'Medium', code: `function copyRandomList(head) {\n    if (!head) return null;\n    const map = new Map();\n    let curr = head;\n    while (curr) { map.set(curr, new Node(curr.val)); curr = curr.next; }\n    curr = head;\n    while (curr) {\n        map.get(curr).next = map.get(curr.next) || null;\n        map.get(curr).random = map.get(curr.random) || null;\n        curr = curr.next;\n    }\n    return map.get(head);\n}` },
        { id: 90, title: 'Word Break II', diff: 'Hard', code: `function wordBreak(s, wordDict) {\n    const map = {};\n    return dfs(s);\n    function dfs(str) {\n        if (map[str]) return map[str];\n        if (str === "") return [""];\n        const res = [];\n        for (let w of wordDict) {\n            if (str.startsWith(w)) {\n                let list = dfs(str.slice(w.length));\n                for (let sub of list) res.push(w + (sub === "" ? "" : " ") + sub);\n            }\n        }\n        return map[str] = res;\n    }\n}` },
        { id: 91, title: 'LRU Cache', diff: 'Medium', code: `class LRUCache {\n    constructor(capacity) { this.cap = capacity; this.map = new Map(); }\n    get(key) {\n        if (!this.map.has(key)) return -1;\n        let val = this.map.get(key); this.map.delete(key); this.map.set(key, val);\n        return val;\n    }\n    put(key, value) {\n        if (this.map.has(key)) this.map.delete(key);\n        this.map.set(key, value);\n        if (this.map.size > this.cap) this.map.delete(this.map.keys().next().value);\n    }\n}` },
        { id: 92, title: 'Sort List', diff: 'Medium', code: `function sortList(head) {\n    if (!head || !head.next) return head;\n    let mid = getMid(head), left = sortList(head), right = sortList(mid);\n    return merge(left, right);\n    function getMid(h) {\n        let slow = null, fast = h;\n        while (fast && fast.next) { slow = slow ? slow.next : h; fast = fast.next.next; }\n        let m = slow.next; slow.next = null; return m;\n    }\n    function merge(l1, l2) {\n        let dummy = new ListNode(), curr = dummy;\n        while (l1 && l2) {\n            if (l1.val < l2.val) { curr.next = l1; l1 = l1.next; }\n            else { curr.next = l2; l2 = l2.next; } curr = curr.next;\n        }\n        curr.next = l1 || l2; return dummy.next;\n    }\n}` },
        { id: 93, title: 'Max Points on a Line', diff: 'Hard', code: `function maxPoints(points) {\n    if (points.length <= 2) return points.length;\n    let res = 0;\n    for (let i = 0; i < points.length; i++) {\n        const map = { "inf": 0 }; let same = 1, local = 0;\n        for (let j = i + 1; j < points.length; j++) {\n            if (points[i][0] === points[j][0] && points[i][1] === points[j][1]) same++;\n            else if (points[i][0] === points[j][0]) map["inf"]++;\n            else {\n                let slope = (points[i][1] - points[j][1]) / (points[i][0] - points[j][0]);\n                map[slope] = (map[slope] || 0) + 1;\n            }\n        }\n        for (let s in map) local = Math.max(local, map[s]);\n        res = Math.max(res, local + same);\n    }\n    return res;\n}` },
        { id: 94, title: 'Find Minimum in Rotated Sorted Array', diff: 'Medium', code: `function findMin(nums) {\n    let lo = 0, hi = nums.length - 1;\n    while (lo < hi) {\n        let mid = Math.floor((lo + hi) / 2);\n        if (nums[mid] > nums[hi]) lo = mid + 1; else hi = mid;\n    }\n    return nums[lo];\n}` },
        { id: 95, title: 'Maximum Product Subarray', diff: 'Medium', code: `function maxProduct(nums) {\n    let res = nums[0], min = nums[0], max = nums[0];\n    for (let i = 1; i < nums.length; i++) {\n        let tmp = max;\n        max = Math.max(nums[i], nums[i] * max, nums[i] * min);\n        min = Math.min(nums[i], nums[i] * tmp, nums[i] * min);\n        res = Math.max(res, max);\n    }\n    return res;\n}` },
        { id: 96, title: 'House Robber', diff: 'Medium', code: `function rob(nums) {\n    let prev1 = 0, prev2 = 0;\n    for (let n of nums) {\n        let tmp = prev1; prev1 = Math.max(prev2 + n, prev1); prev2 = tmp;\n    }\n    return prev1;\n}` },
        { id: 97, title: 'House Robber II', diff: 'Medium', code: `function rob(nums) {\n    if (nums.length === 1) return nums[0];\n    return Math.max(robRange(0, nums.length-2), robRange(1, nums.length-1));\n    function robRange(s, e) {\n        let p1 = 0, p2 = 0;\n        for (let i = s; i <= e; i++) {\n            let t = p1; p1 = Math.max(p2 + nums[i], p1); p2 = t;\n        }\n        return p1;\n    }\n}` },
        { id: 98, title: 'Search a 2D Matrix', diff: 'Medium', code: `function searchMatrix(matrix, target) {\n    let m = matrix.length, n = matrix[0].length, lo = 0, hi = m * n - 1;\n    while (lo <= hi) {\n        let mid = Math.floor((lo + hi) / 2), val = matrix[Math.floor(mid / n)][mid % n];\n        if (val === target) return true;\n        if (val < target) lo = mid + 1; else hi = mid - 1;\n    }\n    return false;\n}` },
        { id: 99, title: 'Search a 2D Matrix II', diff: 'Medium', code: `function searchMatrix(matrix, target) {\n    let r = 0, c = matrix[0].length - 1;\n    while (r < matrix.length && c >= 0) {\n        if (matrix[r][c] === target) return true;\n        if (matrix[r][c] > target) c--; else r++;\n    }\n    return false;\n}` },
        { id: 100, title: 'Container With Most Water', diff: 'Medium', code: `function maxArea(height) {\n    let l = 0, r = height.length - 1, max = 0;\n    while (l < r) {\n        max = Math.max(max, Math.min(height[l], height[r]) * (r - l));\n        height[l] < height[r] ? l++ : r--;\n    }\n    return max;\n}` }
    ];

    // Views
    const VIEWS = {
        home: `
            <section class="c-section c-hero">
                <div class="l-container">
                    <h1 class="c-hero__title">Algorithm Mastery</h1>
                    <p class="u-text-center">100 Essential LeetCode problems remastered in Neon Lime.</p>
                    <div style="margin-top: 2rem;">
                        <a href="#problems" class="c-button c-button--primary" data-link>Enter the Grid</a>
                    </div>
                </div>
            </section>
        `,
        problems: `
            <section class="c-section">
                <div class="l-container">
                    <div class="c-list js-problem-list"></div>
                </div>
            </section>
        `
    };

    const App = {
        init() {
            this.app = document.getElementById('app');
            this.bindEvents();
            this.handleRoute();
            this.initTheme();
        },
        bindEvents() {
            window.addEventListener('hashchange', () => this.handleRoute());
            document.querySelector('.js-theme-toggle').addEventListener('click', () => this.toggleTheme());
        },
        handleRoute() {
            const hash = window.location.hash.slice(1) || 'home';
            this.render(hash);
        },
        render(route) {
            this.app.innerHTML = VIEWS[route] || VIEWS.home;
            document.querySelectorAll('.c-nav__link').forEach(link => {
                link.classList.toggle('is-active', link.getAttribute('href') === '#' + route);
            });
            if (route === 'problems') this.renderProblems();
            window.scrollTo(0, 0);
        },
        renderProblems() {
            const list = document.querySelector('.js-problem-list');
            if (!list) return;
            const fragment = document.createDocumentFragment();
            PROBLEMS.forEach(p => {
                const card = document.createElement('article');
                card.className = 'c-card c-card--list';
                card.innerHTML = `
                    <div class="c-card__header">
                        <span class="c-card__difficulty">${p.diff}</span>
                        <h3 class="c-card__title">#${p.id} ${p.title}</h3>
                    </div>
                    <pre class="c-code-block"><code>${this.escapeHTML(p.code)}</code></pre>
                `;
                fragment.appendChild(card);
            });
            list.appendChild(fragment);
        },
        escapeHTML(str) {
            const p = document.createElement('p');
            p.textContent = str;
            return p.innerHTML;
        },
        initTheme() {
            const saved = localStorage.getItem('leetcode-theme');
            if (saved === 'light') document.body.classList.add('js-theme-light');
        },
        toggleTheme() {
            document.body.classList.toggle('js-theme-light');
            localStorage.setItem('leetcode-theme', document.body.classList.contains('js-theme-light') ? 'light' : 'dark');
        }
    };

    App.init();
})();
